package basic_java;

public class exceptions_class {

	public static void main(String[] args) {
		int a[] = new int[2];
		try {
			int a = 100/0;
			
		} catch (ArithmeticException e) {
			System.out.println(e);
		} catch(Exception e) {
			System.out.println(e);
		}
		
		//using above try catch block doesnt stop the execution of further code 
		System.out.println("---------------------");
		

	}

}
